### ISSUE TITLE
[HELP Wanted]: big sur 出现了以下报错：IOKit Daemon (kernelmanagerd) stall[0], (240s): 'IOUSBHostInterface'

### ISSUE THREAD

**Issue by dingxiaobo** [wy414012/OpenCore-GA-b75#1]
尝试了这个EFI，安装了catalina，非常完美，感谢分享。
想试试big sur，在白果上制作了安装U盘，安装卡在这个报错。
在README里看到建议从catalina升级，但是升级也是卡在这个报错。
![871609224395_ pic_hd](https://user-images.githubusercontent.com/23743074/103264270-2f030e80-49e5-11eb-9430-aead0efa304c.jpg)

做了以下尝试，报错均未变化
- 禁用`SSDT-USBX.aml` `SSDT-USB-Reset.aml`
- 禁用`USBMap.kext`
- 删除`Broadcom BCM57785 patch`(我没有BCM网卡)

技穷了，求助求助

**Comment by wy414012** [comment]
升级efi版本即可解决
