### ISSUE TITLE
卡在IOTimeSyncLocalClockPort::handleGeneralNotification<ptr>

### ISSUE THREAD

**Issue by zmh1288** [wy414012/OpenCore-GA-b75#2]
首先感谢作者的无私分享，使用2.0.5版本的EFI正常，更新到2.0.6就不能使用，会卡在这里或者自动重启，原因不明。
配置，B75M-D3V , E3-1230V2 , RX560,没有无线网卡
![QQ图片20210728163521](https://user-images.githubusercontent.com/62844929/127291909-2640e658-6a9f-4360-a871-23bd40331779.jpg)

**Comment by wy414012** [comment]
@zmh1288 在你自己设备上重新自定义定制下usb端口，可能我在2.0.6定制时候的bug

**Comment by wy414012** [comment]
@zmh1288  https://github.com/wy414012/OpenCore-GA-b75/commit/709a2f4b9f85209e1a1e5d7ddd66ac03cb03cbdd 尝试最新的该提交

**Comment by zmh1288** [comment]
现在好了，感谢作者

**Comment by wy414012** [comment]
@zmh1288 那么现在关闭该问题了！
