### ISSUE TITLE
有线网卡无法驱动

### ISSUE THREAD

**Issue by fengcms** [wy414012/OpenCore-GA-b75#3]
有线网卡无法驱动，设备里找不到PCI设备。请问要怎么处理呢

**Comment by wy414012** [comment]
@fengcms 首先你要确定自己硬件是什么，并且没使用过原版RTL8168 2.4.0+以上版本驱动，还需要确认自己硬件是否损坏

**Comment by fengcms** [comment]
你好，感谢您的回复，我的主板为下图的型号，只使用了你的EFI文件进行引导，并未进行其他调整。在WinPE 系统下面，网络是可以正常链接的。

我的大体配置为 e1230v2 + ga b75 主板 + 16G 内存 + G650 英伟达显卡。目前除有线网卡外，其他均正常。

查询资料，网卡为 Atheros 品牌的，未查询到具体型号。技嘉官网资料 https://www.gigabyte.com/Motherboard/GA-B75-D3V-rev-12/sp#sp

希望高手指导一下，应该怎么处理。谢谢

![image](https://user-images.githubusercontent.com/15262264/147846116-ec4c6032-dce2-43bf-88e3-c2a5ed4b7f1d.png)

![image](https://user-images.githubusercontent.com/15262264/147846127-154b90c2-b8ee-48f9-9895-9367cf5795ba.png)

![image](https://user-images.githubusercontent.com/15262264/147846134-1e60e625-b630-4c5c-91de-d4603e21f75f.png)
![image](https://user-images.githubusercontent.com/15262264/147846144-36d90c1f-a069-4073-b43d-f64a903cb719.png)

**Comment by fengcms** [comment]
大家好，我在 https://mackie100projects.altervista.org/occ-changelog-version-2-54-0-0/ 这个地址下载了 OCC 编辑器

然后在 https://github.com/Mieze/AtherosE2200Ethernet/releases/tag/2.2.2 下载了 AtherosE2200Ethernet 这个驱动，放到EFI 磁盘的 EFI →OC → Kexts 目录下面。

用 OCC 编辑器 打开 EFI → EFI → OC → config.plist 文件，并把 AtherosE2200Ethernet 拖动到 OCC 编辑器里面，如下图所示：

![image](https://user-images.githubusercontent.com/15262264/147847239-f1c6f18a-344d-472a-aa17-e3b39665b7d5.png)

（由于是另外一台电脑，所以上图只是演示）

然后重启电脑，有线网卡顺利被驱动了。

现在想问，还有其他需要操作的步骤吗？

**Comment by wy414012** [comment]
@fengcms 不需要进行额外操作，唯一还要做的一件事情是删除EFI中自带的螃蟹网卡避免引起一些不必要的异常

**Comment by fengcms** [comment]
意思是，删除 RealtekRTL8111.kext 这个文件，另外在OCC编辑器中，将这个给删掉，就可以了是吗？

**Comment by wy414012** [comment]
是的

**Comment by fengcms** [comment]
感谢！
